import { Injectable } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';

@Injectable()
export class CategoryService {
  constructor(private httpService: HttpService) {}

  checkCategory(item: any, result: any[], keyword: string): any[] {
    for (let i = 0; i < item.data.data.cards.length; i++) {
      if (item.data.data.cards[i].styles.includes(keyword)) {
        result.push(item.data.data.cards[i]);
      }
    }
    return result;
  }

  async getCategory(): Promise<any> {
    return {
      code: 0,
      message: '0',
      ttl: 1,
      data: {
        is_end: false,
        cards: [
          {
            type: 'ogv',
            card_type: 'ogv_anime',
            title: 'ผ่าพิภพไททัน (พากย์ไทย)',
            cover:
              'https://pic.bstarstatic.com/ogv/9beb60c3f8867dc5b35c9c8a4fbfa08ad5d1f23e.png',
            view: '6.3M วิว',
            styles: '',
            style_list: ['แฟนตาซี', 'ต่อสู้'],
            season_id: '1004201',
            episode_id: '',
            index_show: 'เสร็จแล้ว',
            label: 1,
            rank_info: null,
            view_history: null,
            watched: '',
            duration: '',
            view_at: '',
            pub_time_text: '',
            pub_time_ts: 0,
            is_favored: false,
            unavailable: false,
          },
          {
            type: 'ogv',
            card_type: 'ogv_anime',
            title: 'เทพเกรียน โรงเรียนมัธยม',
            cover:
              'https://pic.bstarstatic.com/ogv/d3d8145721020897b3e515fa7d63bb07b6db94c3.png',
            view: '9.7M วิว',
            styles: '',
            style_list: ['แฟนตาซี', 'โรงเรียน'],
            season_id: '36446',
            episode_id: '',
            index_show: 'เสร็จแล้ว',
            label: 0,
            rank_info: null,
            view_history: null,
            watched: '',
            duration: '',
            view_at: '',
            pub_time_text: '',
            pub_time_ts: 0,
            is_favored: false,
            unavailable: false,
          },
          {
            type: 'ogv',
            card_type: 'ogv_anime',
            title: 'หวานใจนายตัวป่วน',
            cover:
              'https://pic.bstarstatic.com/ogv/beb898f09550c72ea01f3390d4f0d11d150493aa.png',
            view: '8.3M วิว',
            styles: '',
            style_list: ['ชีวิตประจำวัน', 'โรงเรียน'],
            season_id: '1008193',
            episode_id: '',
            index_show: 'เสร็จแล้ว',
            label: 0,
            rank_info: null,
            view_history: null,
            watched: '',
            duration: '',
            view_at: '',
            pub_time_text: '',
            pub_time_ts: 0,
            is_favored: false,
            unavailable: false,
          },
          {
            type: 'ogv',
            card_type: 'ogv_anime',
            title: 'ยุทธศาสตร์กู้ชาติของราชามือใหม่ ภาคที่ 2',
            cover:
              'https://pic.bstarstatic.com/ogv/3dca6d6a57c6acdc37c91873f3c40b41b08e8e93.jpg',
            view: '8.3M วิว',
            styles: '',
            style_list: ['แฟนตาซี', 'ผจญภัย'],
            season_id: '1035690',
            episode_id: '',
            index_show: 'เสร็จแล้ว',
            label: 0,
            rank_info: null,
            view_history: null,
            watched: '',
            duration: '',
            view_at: '',
            pub_time_text: '',
            pub_time_ts: 0,
            is_favored: false,
            unavailable: false,
          },
          {
            type: 'ogv',
            card_type: 'ogv_anime',
            title: 'Stand My Heroes: Piece of Truth',
            cover:
              'https://pic.bstarstatic.com/ogv/55de56bfd23647de7122cfd190aded08e5767cff.png',
            view: '53.3K วิว',
            styles: '',
            style_list: ['สืบสวนสอบสวน', 'โรแมนติก'],
            season_id: '34846',
            episode_id: '',
            index_show: 'เสร็จแล้ว',
            label: 0,
            rank_info: null,
            view_history: null,
            watched: '',
            duration: '',
            view_at: '',
            pub_time_text: '',
            pub_time_ts: 0,
            is_favored: false,
            unavailable: false,
          },
          {
            type: 'ogv',
            card_type: 'ogv_anime',
            title:
              'Tensei Kenja no Isekai Life: Daini no Shokugyo o Ete, Sekai Saikyo ni Narimashita',
            cover:
              'https://pic.bstarstatic.com/ogv/366d5210e1199836f96816e3ded2a2afcae54c48.png',
            view: '18.6M วิว',
            styles: '',
            style_list: ['แฟนตาซี', 'ต่อสู้'],
            season_id: '1061248',
            episode_id: '',
            index_show: 'เสร็จแล้ว',
            label: 0,
            rank_info: null,
            view_history: null,
            watched: '',
            duration: '',
            view_at: '',
            pub_time_text: '',
            pub_time_ts: 0,
            is_favored: false,
            unavailable: false,
          },
          {
            type: 'ogv',
            card_type: 'ogv_anime',
            title: 'แด่เธอผู้เป็นนิรันดร์ ภาคที่ 2',
            cover:
              'https://pic.bstarstatic.com/ogv/bf722752869c048967572b42482ef310d9dc4249.jpg',
            view: '118.1K วิว',
            styles: '',
            style_list: ['แฟนตาซี', 'ผจญภัย'],
            season_id: '2069206',
            episode_id: '',
            index_show: 'เร็ว ๆ นี้',
            label: 0,
            rank_info: null,
            view_history: null,
            watched: '',
            duration: '',
            view_at: '',
            pub_time_text: '',
            pub_time_ts: 0,
            is_favored: false,
            unavailable: false,
          },
          {
            type: 'ogv',
            card_type: 'ogv_anime',
            title: 'Asatte no Houkou ปลายทางแห่งคำอธิษฐาน',
            cover:
              'https://pic.bstarstatic.com/ogv/d1d82bf945d2cf3c32ae99321d5fae3bbf60e3e0.png',
            view: '3.0K วิว',
            styles: '',
            style_list: ['ชีวิตประจำวัน', 'แฟนตาซี'],
            season_id: '35483',
            episode_id: '',
            index_show: 'เสร็จแล้ว',
            label: 0,
            rank_info: null,
            view_history: null,
            watched: '',
            duration: '',
            view_at: '',
            pub_time_text: '',
            pub_time_ts: 0,
            is_favored: false,
            unavailable: false,
          },
          {
            type: 'ogv',
            card_type: 'ogv_anime',
            title: '“รัน” สาวน้อยพลังจิต, Telepathy Shōjo Ran Jiken Note',
            cover:
              'https://pic.bstarstatic.com/ogv/6eca1dab0351f00ec8d8c480a0bdee29dcf038e2.png',
            view: '6.7K วิว',
            styles: '',
            style_list: ['แฟนตาซี', 'ดราม่า'],
            season_id: '35231',
            episode_id: '',
            index_show: 'เสร็จแล้ว',
            label: 0,
            rank_info: null,
            view_history: null,
            watched: '',
            duration: '',
            view_at: '',
            pub_time_text: '',
            pub_time_ts: 0,
            is_favored: false,
            unavailable: false,
          },
          {
            type: 'ogv',
            card_type: 'ogv_anime',
            title: 'ม็อบไซโค 100 คนพลังจิต ซีซั่น 3',
            cover:
              'https://pic.bstarstatic.com/ogv/b7cdbaf0bff697a212767b5102e11749f40c60e9.png',
            view: '1.5M วิว',
            styles: '',
            style_list: ['ชีวิตประจำวัน', 'โรงเรียน'],
            season_id: '2067476',
            episode_id: '',
            index_show: 'อัปเดตเป็นตอนที่ 3',
            label: 0,
            rank_info: null,
            view_history: null,
            watched: '',
            duration: '',
            view_at: '',
            pub_time_text: '',
            pub_time_ts: 0,
            is_favored: false,
            unavailable: false,
          },
          {
            type: 'ogv',
            card_type: 'ogv_anime',
            title: 'พี่น้องปริศนาโรงเรียนมหาเวท ภาคที่ 2',
            cover:
              'https://pic.bstarstatic.com/ogv/3e926e64dd0456618111c2e79ccfcb64a7d3989d.png',
            view: '3.7M วิว',
            styles: '',
            style_list: ['Sci-fi/ไซ-ไฟ', 'โรงเรียน'],
            season_id: '1004816',
            episode_id: '',
            index_show: 'เสร็จแล้ว',
            label: 1,
            rank_info: null,
            view_history: null,
            watched: '',
            duration: '',
            view_at: '',
            pub_time_text: '',
            pub_time_ts: 0,
            is_favored: false,
            unavailable: false,
          },
          {
            type: 'ogv',
            card_type: 'ogv_anime',
            title: 'สำนักงานป่วนก๊วนหลุดโลก',
            cover:
              'https://pic.bstarstatic.com/ogv/9a414ccd11ea1f214f2e37263028025fa3f0cdb7.jpg',
            view: '425.7K วิว',
            styles: '',
            style_list: ['ชีวิตประจำวัน', 'ตลก'],
            season_id: '36419',
            episode_id: '',
            index_show: 'เสร็จแล้ว',
            label: 0,
            rank_info: null,
            view_history: null,
            watched: '',
            duration: '',
            view_at: '',
            pub_time_text: '',
            pub_time_ts: 0,
            is_favored: false,
            unavailable: false,
          },
          {
            type: 'ogv',
            card_type: 'ogv_anime',
            title: 'หนุ่มเย็บผ้ากับสาวนักคอสเพลย์ (พากย์ไทย)',
            cover:
              'https://pic.bstarstatic.com/ogv/9a30c60b8c9d4570e8d7d377ef5af8cfbcb98429.jpg',
            view: '490.0K วิว',
            styles: '',
            style_list: ['ตลก', 'ดราม่า'],
            season_id: '1058105',
            episode_id: '',
            index_show: 'เสร็จแล้ว',
            label: 2,
            rank_info: null,
            view_history: null,
            watched: '',
            duration: '',
            view_at: '',
            pub_time_text: '',
            pub_time_ts: 0,
            is_favored: false,
            unavailable: false,
          },
          {
            type: 'ogv',
            card_type: 'ogv_anime',
            title: 'Karin',
            cover:
              'https://pic.bstarstatic.com/ogv/f3a718f9ebff0e79d0eb52d386a39e8de295e079.jpg',
            view: '55.8K วิว',
            styles: '',
            style_list: ['โรงเรียน', 'ตลก'],
            season_id: '35429',
            episode_id: '',
            index_show: 'เสร็จแล้ว',
            label: 0,
            rank_info: null,
            view_history: null,
            watched: '',
            duration: '',
            view_at: '',
            pub_time_text: '',
            pub_time_ts: 0,
            is_favored: false,
            unavailable: false,
          },
          {
            type: 'ogv',
            card_type: 'ogv_anime',
            title: 'Gun x Sword',
            cover:
              'https://pic.bstarstatic.com/ogv/d9ad66fe2361b65c2b820be5fc23cdf95e7d2305.png',
            view: '10.8K วิว',
            styles: '',
            style_list: ['Sci-fi/ไซ-ไฟ', 'ต่อสู้'],
            season_id: '35869',
            episode_id: '',
            index_show: 'เสร็จแล้ว',
            label: 0,
            rank_info: null,
            view_history: null,
            watched: '',
            duration: '',
            view_at: '',
            pub_time_text: '',
            pub_time_ts: 0,
            is_favored: false,
            unavailable: false,
          },
          {
            type: 'ogv',
            card_type: 'ogv_anime',
            title: 'Boku no Kanojo ga Majimesugiru Sho-bitch na Ken',
            cover:
              'https://pic.bstarstatic.com/ogv/f37de33dd20bf456c83e78f001b8c890c3929d24.png',
            view: '3.1M วิว',
            styles: '',
            style_list: ['ชีวิตประจำวัน', 'โรงเรียน'],
            season_id: '35615',
            episode_id: '',
            index_show: 'เสร็จแล้ว',
            label: 1,
            rank_info: null,
            view_history: null,
            watched: '',
            duration: '',
            view_at: '',
            pub_time_text: '',
            pub_time_ts: 0,
            is_favored: false,
            unavailable: false,
          },
          {
            type: 'ogv',
            card_type: 'ogv_anime',
            title: 'แด่เธอผู้เป็นนิรันดร์',
            cover:
              'https://pic.bstarstatic.com/ogv/36157d5dea81cacce6c496f7c86af2b6129fdf65.png',
            view: '8.5M วิว',
            styles: '',
            style_list: ['แฟนตาซี', 'ผจญภัย'],
            season_id: '1002225',
            episode_id: '',
            index_show: 'เสร็จแล้ว',
            label: 0,
            rank_info: null,
            view_history: null,
            watched: '',
            duration: '',
            view_at: '',
            pub_time_text: '',
            pub_time_ts: 0,
            is_favored: false,
            unavailable: false,
          },
          {
            type: 'ogv',
            card_type: 'ogv_anime',
            title: 'Pani Poni',
            cover:
              'https://pic.bstarstatic.com/ogv/559d3b5812cddd105f3dfabfe69e22486237f29f.png',
            view: '6.3K วิว',
            styles: '',
            style_list: ['ชีวิตประจำวัน', 'โรงเรียน'],
            season_id: '34986',
            episode_id: '',
            index_show: 'เสร็จแล้ว',
            label: 0,
            rank_info: null,
            view_history: null,
            watched: '',
            duration: '',
            view_at: '',
            pub_time_text: '',
            pub_time_ts: 0,
            is_favored: false,
            unavailable: false,
          },
          {
            type: 'ogv',
            card_type: 'ogv_anime',
            title: 'แฟ้มลับคดีเด็กหาย',
            cover:
              'https://pic.bstarstatic.com/ogv/a78253f65efbbe8446c6cef8b3697261491c6f9b.png',
            view: '1.1M วิว',
            styles: '',
            style_list: ['Sci-fi/ไซ-ไฟ', 'โรงเรียน'],
            season_id: '34681',
            episode_id: '',
            index_show: 'เสร็จแล้ว',
            label: 1,
            rank_info: null,
            view_history: null,
            watched: '',
            duration: '',
            view_at: '',
            pub_time_text: '',
            pub_time_ts: 0,
            is_favored: false,
            unavailable: false,
          },
          {
            type: 'ogv',
            card_type: 'ogv_anime',
            title: 'เพราะพระเจ้าเลือกเลยได้เกิดใหม่มาเลี้ยงสไลม์ในต่างโลก',
            cover:
              'https://pic.bstarstatic.com/ogv/b1f87920e51147afaf240e193be4f3195319ce0d.png',
            view: '6.7M วิว',
            styles: '',
            style_list: ['ชีวิตประจำวัน', 'แฟนตาซี'],
            season_id: '1004516',
            episode_id: '',
            index_show: 'เสร็จแล้ว',
            label: 0,
            rank_info: null,
            view_history: null,
            watched: '',
            duration: '',
            view_at: '',
            pub_time_text: '',
            pub_time_ts: 0,
            is_favored: false,
            unavailable: false,
          },
          {
            type: 'ogv',
            card_type: 'ogv_anime',
            title: 'Mahou Shoujo Nante Mou Ii Desukara. Second Season ภาค2',
            cover:
              'https://pic.bstarstatic.com/ogv/e990c571f87303a0d3e030cb5579c50645c68641.png',
            view: '7.4K วิว',
            styles: '',
            style_list: ['ชีวิตประจำวัน', 'เวทมนตร์'],
            season_id: '34836',
            episode_id: '',
            index_show: 'เสร็จแล้ว',
            label: 0,
            rank_info: null,
            view_history: null,
            watched: '',
            duration: '',
            view_at: '',
            pub_time_text: '',
            pub_time_ts: 0,
            is_favored: false,
            unavailable: false,
          },
          {
            type: 'ogv',
            card_type: 'ogv_anime',
            title: 'Sonny Boy',
            cover:
              'https://pic.bstarstatic.com/ogv/11a591dd6c69f5724fab94ec0f227037a2327791.jpg',
            view: '389.4K วิว',
            styles: '',
            style_list: ['แฟนตาซี', 'โรงเรียน'],
            season_id: '1010705',
            episode_id: '',
            index_show: 'เสร็จแล้ว',
            label: 0,
            rank_info: null,
            view_history: null,
            watched: '',
            duration: '',
            view_at: '',
            pub_time_text: '',
            pub_time_ts: 0,
            is_favored: false,
            unavailable: false,
          },
          {
            type: 'ogv',
            card_type: 'ogv_anime',
            title: 'โจโจ้ ล่าข้ามศตวรรษ ภาคที่ 3 ภาคนักรบประกายดาว',
            cover:
              'https://pic.bstarstatic.com/ogv/8fafc9af5cfe7f12adfb559fd7fef019090e2d46.png',
            view: '5.0M วิว',
            styles: '',
            style_list: ['แฟนตาซี', 'ผจญภัย'],
            season_id: '35259',
            episode_id: '',
            index_show: 'เสร็จแล้ว',
            label: 1,
            rank_info: null,
            view_history: null,
            watched: '',
            duration: '',
            view_at: '',
            pub_time_text: '',
            pub_time_ts: 0,
            is_favored: false,
            unavailable: false,
          },
          {
            type: 'ogv',
            card_type: 'ogv_anime',
            title: 'ผู้กล้าโล่ผงาด',
            cover:
              'https://pic.bstarstatic.com/ogv/3fdc139e9426881351673e5dfc4c03010862bb7b.png',
            view: '24.0M วิว',
            styles: '',
            style_list: ['แฟนตาซี', 'ผจญภัย'],
            season_id: '34975',
            episode_id: '',
            index_show: 'เสร็จแล้ว',
            label: 0,
            rank_info: null,
            view_history: null,
            watched: '',
            duration: '',
            view_at: '',
            pub_time_text: '',
            pub_time_ts: 0,
            is_favored: false,
            unavailable: false,
          },
          {
            type: 'ogv',
            card_type: 'ogv_anime',
            title: 'Kin`iro Mosaic',
            cover:
              'https://pic.bstarstatic.com/ogv/2cd232b27f77d7befa6810f08beadd0641724f4f.png',
            view: '10.6K วิว',
            styles: '',
            style_list: ['ชีวิตประจำวัน', 'โรงเรียน'],
            season_id: '35153',
            episode_id: '',
            index_show: 'เสร็จแล้ว',
            label: 0,
            rank_info: null,
            view_history: null,
            watched: '',
            duration: '',
            view_at: '',
            pub_time_text: '',
            pub_time_ts: 0,
            is_favored: false,
            unavailable: false,
          },
          {
            type: 'ogv',
            card_type: 'ogv_anime',
            title: 'Juuou Mujin no Fafnir',
            cover:
              'https://pic.bstarstatic.com/ogv/480e35f2f37d83748fb961f977b217c19ab8c168.png',
            view: '342.8K วิว',
            styles: '',
            style_list: ['แฟนตาซี', 'โรงเรียน'],
            season_id: '36334',
            episode_id: '',
            index_show: 'เสร็จแล้ว',
            label: 0,
            rank_info: null,
            view_history: null,
            watched: '',
            duration: '',
            view_at: '',
            pub_time_text: '',
            pub_time_ts: 0,
            is_favored: false,
            unavailable: false,
          },
          {
            type: 'ogv',
            card_type: 'ogv_anime',
            title: 'ฝ่าปริศนาตะลุยโลกเบื้องหลัง',
            cover:
              'https://pic.bstarstatic.com/ogv/234526704d05e0b95bb5d97c67071642e94e6c2f.jpg',
            view: '630.7K วิว',
            styles: '',
            style_list: ['Sci-fi/ไซ-ไฟ', 'ผจญภัย'],
            season_id: '36940',
            episode_id: '',
            index_show: 'เสร็จแล้ว',
            label: 1,
            rank_info: null,
            view_history: null,
            watched: '',
            duration: '',
            view_at: '',
            pub_time_text: '',
            pub_time_ts: 0,
            is_favored: false,
            unavailable: false,
          },
          {
            type: 'ogv',
            card_type: 'ogv_anime',
            title:
              'มันผิดรึไงถ้าใจอยากจะพบรักในดันเจี้ยน เดอะมูฟวี่ Arrow of the Orion',
            cover:
              'https://pic.bstarstatic.com/ogv/b0077add30b818632b1212ffef55e8530fb14abf.png',
            view: '845.8K วิว',
            styles: '',
            style_list: ['แฟนตาซี', 'ผจญภัย'],
            season_id: '34487',
            episode_id: '',
            index_show: 'เสร็จแล้ว',
            label: 1,
            rank_info: null,
            view_history: null,
            watched: '',
            duration: '',
            view_at: '',
            pub_time_text: '',
            pub_time_ts: 0,
            is_favored: false,
            unavailable: false,
          },
          {
            type: 'ogv',
            card_type: 'ogv_anime',
            title:
              'Dokkoida?! Sumeba Miyako no Cosmos-sou Suttoko Taisen Dokkoida',
            cover:
              'https://pic.bstarstatic.com/ogv/69992df476858a39ebe9362b9c1e3e7b2ae02a2a.png',
            view: '2.0K วิว',
            styles: '',
            style_list: ['ชีวิตประจำวัน', 'ตลก'],
            season_id: '35002',
            episode_id: '',
            index_show: 'เสร็จแล้ว',
            label: 0,
            rank_info: null,
            view_history: null,
            watched: '',
            duration: '',
            view_at: '',
            pub_time_text: '',
            pub_time_ts: 0,
            is_favored: false,
            unavailable: false,
          },
          {
            type: 'ogv',
            card_type: 'ogv_anime',
            title: 'DOG DAYS',
            cover:
              'https://pic.bstarstatic.com/ogv/48be247422f88f697fb6e87561abdcf105cdb286.jpg',
            view: '446.4K วิว',
            styles: '',
            style_list: ['ฮาเร็ม', 'แฟนตาซี'],
            season_id: '35564',
            episode_id: '',
            index_show: 'เสร็จแล้ว',
            label: 0,
            rank_info: null,
            view_history: null,
            watched: '',
            duration: '',
            view_at: '',
            pub_time_text: '',
            pub_time_ts: 0,
            is_favored: false,
            unavailable: false,
          },
        ],
      },
    };
  }
}
